version: '2'
services:
    sekc-app:
        image: sekc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://sekc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sekc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sekc-mongodb:
        extends:
            file: mongodb.yml
            service: sekc-mongodb
